config/routes.rb
Elections::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :votes

  resources :users

  resources :electoral_districts

  resources :voivodship_committees

  resources :voivodships do
    resources :electoral_districts
  end

  resources :committees

end

app/models/electoral_district.rb
class ElectoralDistrict < ActiveRecord::Base
  belongs_to :voivodship
  attr_accessible :name, :valid_votes, :invalid_votes, :voivodship_id, :number_of_voters
  has_many :votes
  has_one :user

  validates :name, presence: true, uniqueness: true
  validates :valid_votes, numericality: true
  validates :invalid_votes, numericality: true

end

app/controllers/electoral_districts_controller.rb
class ElectoralDistrictsController < ApplicationController
  # GET /electoral_districts
  # GET /electoral_districts.json
  def index
    @electoral_districts = ElectoralDistrict.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @electoral_districts }
    end
  end

  # GET /electoral_districts/1
  # GET /electoral_districts/1.json
  def show
    @electoral_district = ElectoralDistrict.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @electoral_district }
    end
  end

  # GET /electoral_districts/new
  # GET /electoral_districts/new.json
  def new
    @electoral_district = ElectoralDistrict.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @electoral_district }
    end
  end

  # GET /electoral_districts/1/edit
  def edit
    @electoral_district = ElectoralDistrict.find(params[:id])
  end

  # POST /electoral_districts
  # POST /electoral_districts.json
  def create
    @electoral_district = ElectoralDistrict.new(params[:electoral_district])

    respond_to do |format|
      if @electoral_district.save
        format.html { redirect_to @electoral_district, notice: 'Electoral district was successfully created.' }
        format.json { render json: @electoral_district, status: :created, location: @electoral_district }
      else
        format.html { render action: "new" }
        format.json { render json: @electoral_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /electoral_districts/1
  # PUT /electoral_districts/1.json
  def update
    @electoral_district = ElectoralDistrict.find(params[:id])

    respond_to do |format|
      if @electoral_district.update_attributes(params[:electoral_district])
        format.html { redirect_to @electoral_district, notice: 'Electoral district was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @electoral_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electoral_districts/1
  # DELETE /electoral_districts/1.json
  def destroy
    @electoral_district = ElectoralDistrict.find(params[:id])
    @electoral_district.destroy

    respond_to do |format|
      format.html { redirect_to electoral_districts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/electoral_districts_helper.rb
module ElectoralDistrictsHelper
end

app/views/electoral_districts/_form.html.erb
<%= form_for(@electoral_district) do |f| %>
  <% if @electoral_district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@electoral_district.errors.count, "error") %> prohibited this electoral_district from being saved:</h2>

      <ul>
      <% @electoral_district.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :valid_votes %><br />
    <%= f.number_field :valid_votes %>
  </div>
  <div class="field">
    <%= f.label :voivodship %><br />
    <%= f.text_field :voivodship %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/electoral_districts/edit.html.erb
<h1>Editing electoral_district</h1>

<%= render 'form' %>

<%= link_to 'Show', @electoral_district %> |
<%= link_to 'Back', electoral_districts_path %>

app/views/electoral_districts/index.html.erb
<h1>Listing electoral_districts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Valid votes</th>
    <th>Voivodship</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @electoral_districts.each do |electoral_district| %>
  <tr>
    <td><%= electoral_district.name %></td>
    <td><%= electoral_district.valid_votes %></td>
    <td><%= electoral_district.voivodship %></td>
    <td><%= link_to 'Show', electoral_district %></td>
    <td><%= link_to 'Edit', edit_electoral_district_path(electoral_district) %></td>
    <td><%= link_to 'Destroy', electoral_district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Electoral district', new_electoral_district_path %>

app/views/electoral_districts/new.html.erb
<h1>New electoral_district</h1>

<%= render 'form' %>

<%= link_to 'Back', electoral_districts_path %>

app/views/electoral_districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @electoral_district.name %>
</p>

<p>
  <b>Valid votes:</b>
  <%= @electoral_district.valid_votes %>
</p>

<p>
  <b>Voivodship:</b>
  <%= @electoral_district.voivodship %>
</p>


<%= link_to 'Edit', edit_electoral_district_path(@electoral_district) %> |
<%= link_to 'Back', electoral_districts_path %>