config/routes.rb
Elections::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :votes

  resources :users

  resources :electoral_districts

  resources :voivodship_committees

  resources :voivodships do
    resources :electoral_districts
  end

  resources :committees

end

app/models/voivodship.rb
class Voivodship < ActiveRecord::Base
  has_many :electoral_districts
  has_and_belongs_to_many :committees
  attr_accessible :name, :sejmik_size, :committee_ids

  accepts_nested_attributes_for :committees

  validates :name, presence: true, uniqueness: true

end

app/controllers/voivodships_controller.rb
class VoivodshipsController < ApplicationController
  # GET /voivodships
  # GET /voivodships.json
  def index
    @voivodships = Voivodship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voivodships }
    end
  end

  # GET /voivodships/1
  # GET /voivodships/1.json
  def show
    @voivodship = Voivodship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voivodship }
    end
  end

  # GET /voivodships/new
  # GET /voivodships/new.json
  def new
    @voivodship = Voivodship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voivodship }
    end
  end

  # GET /voivodships/1/edit
  def edit
    @voivodship = Voivodship.find(params[:id])
  end

  # POST /voivodships
  # POST /voivodships.json
  def create
    @voivodship = Voivodship.new(params[:voivodship])

    respond_to do |format|
      if @voivodship.save
        format.html { redirect_to @voivodship, notice: 'Voivodship was successfully created.' }
        format.json { render json: @voivodship, status: :created, location: @voivodship }
      else
        format.html { render action: "new" }
        format.json { render json: @voivodship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voivodships/1
  # PUT /voivodships/1.json
  def update
    @voivodship = Voivodship.find(params[:id])

    respond_to do |format|
      if @voivodship.update_attributes(params[:voivodship])
        format.html { redirect_to @voivodship, notice: 'Voivodship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voivodship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voivodships/1
  # DELETE /voivodships/1.json
  def destroy
    @voivodship = Voivodship.find(params[:id])
    @voivodship.destroy

    respond_to do |format|
      format.html { redirect_to voivodships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/voivodships_helper.rb
module VoivodshipsHelper
end

app/views/voivodships/_form.html.erb
<%= form_for(@voivodship) do |f| %>
  <% if @voivodship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voivodship.errors.count, "error") %> prohibited this voivodship from being saved:</h2>

      <ul>
      <% @voivodship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voivodships/edit.html.erb
<h1>Editing voivodship</h1>

<%= render 'form' %>

<%= link_to 'Show', @voivodship %> |
<%= link_to 'Back', voivodships_path %>

app/views/voivodships/index.html.erb
<h1>Listing voivodships</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @voivodships.each do |voivodship| %>
  <tr>
    <td><%= voivodship.name %></td>
    <td><%= link_to 'Show', voivodship %></td>
    <td><%= link_to 'Edit', edit_voivodship_path(voivodship) %></td>
    <td><%= link_to 'Destroy', voivodship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Voivodship', new_voivodship_path %>

app/views/voivodships/new.html.erb
<h1>New voivodship</h1>

<%= render 'form' %>

<%= link_to 'Back', voivodships_path %>

app/views/voivodships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @voivodship.name %>
</p>


<%= link_to 'Edit', edit_voivodship_path(@voivodship) %> |
<%= link_to 'Back', voivodships_path %>