config/routes.rb
Elections::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :votes

  resources :users

  resources :electoral_districts

  resources :voivodship_committees

  resources :voivodships do
    resources :electoral_districts
  end

  resources :committees

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  has_many :votes
  has_and_belongs_to_many :voivodships
  has_attached_file :logo, :styles => { :medium => "238x238>", 
                                   :thumb => "100x100>"
                                 }
  do_not_validate_attachment_file_type :logo_file_name

  

  attr_accessible :name, :logo_name, :logo_filepath, :logo_fileurl, :voivodship_ids, :image, :logo, :logo_file_name

  validates :name, presence: true, uniqueness: true



 

end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @committees }
    end
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
    @committee = Committee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @committee }
    end
  end

  # GET /committees/new
  # GET /committees/new.json
  def new
    @committee = Committee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @committee }
    end
  end

  # GET /committees/1/edit
  def edit
    @committee = Committee.find(params[:id])
  end

  # POST /committees
  # POST /committees.json
  def create
    @committee = Committee.new(params[:committee])

    respond_to do |format|
      if @committee.save
        format.html { redirect_to @committee, notice: 'Committee was successfully created.' }
        format.json { render json: @committee, status: :created, location: @committee }
      else
        format.html { render action: "new" }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /committees/1
  # PUT /committees/1.json
  def update
    @committee = Committee.find(params[:id])

    respond_to do |format|
      if @committee.update_attributes(params[:committee])
        format.html { redirect_to @committee, notice: 'Committee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee = Committee.find(params[:id])
    @committee.destroy

    respond_to do |format|
      format.html { redirect_to committees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing committee</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<h1>Listing committees</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @committees.each do |committee| %>
  <tr>
    <td><%= committee.name %></td>
    <td><%= link_to 'Show', committee %></td>
    <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
    <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Committee', new_committee_path %>

app/views/committees/new.html.erb
<h1>New committee</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @committee.name %>
</p>



<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>